In [2]:
import pandas as pd

In [3]:
jan = "Resources/2018_01.csv"
feb = "Resources/2018_02.csv"
mar = "Resources/2018_03.csv"
apr = "Resources/2018_04.csv"
may = "Resources/2018_05.csv"
jun = "Resources/2018_06.csv"
jul = "Resources/2018_07.csv"
aug = "Resources/2018_08.csv"
sep = "Resources/2018_09.csv"
oct = "Resources/2018_10.csv"
nov = "Resources/2018_11.csv"
dec = "Resources/2018_12.csv"

months = [jan, feb, mar, apr, may, jun, jul, aug, sep, oct, nov, dec]

In [4]:
jan_df = pd.read_csv(jan)

new_jan = jan_df[['starttime','tripduration', 'usertype', 'birth year']]

newer_jan = new_jan.dropna()

newerer_jan = newer_jan.rename(columns={'tripduration': 'Trip Duration',
                                        'starttime': 'Start Time',
                                        'usertype': 'User Type',
                                        'birth year': 'Birth Year'})
newerer_jan['Age'] = 2018 - (newerer_jan['Birth Year'])

newest_jan = newerer_jan.drop(columns=['Birth Year'])
newest_jan['Start Time'] = pd.to_datetime(newest_jan['Start Time'])
newest_jan['Start Time'] = newest_jan['Start Time'].dt.round('1s')
newest_jan['Start Time'] = newest_jan['Start Time'].dt.time
#newest_jan.head()

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,771,2018-02-01 00:14:16.4120,2018-02-01 00:27:08.2290,72,W 52 St & 11 Ave,40.767272,-73.993929,379,W 31 St & 7 Ave,40.749156,-73.991600,14536,Subscriber,1952,1
1,264,2018-02-01 05:14:45.1790,2018-02-01 05:19:09.6860,72,W 52 St & 11 Ave,40.767272,-73.993929,478,11 Ave & W 41 St,40.760301,-73.998842,32820,Subscriber,1965,1
2,819,2018-02-01 06:48:55.2290,2018-02-01 07:02:35.0290,72,W 52 St & 11 Ave,40.767272,-73.993929,405,Washington St & Gansevoort St,40.739323,-74.008119,16131,Subscriber,1968,1
3,646,2018-02-01 07:12:50.1740,2018-02-01 07:23:36.5280,72,W 52 St & 11 Ave,40.767272,-73.993929,2006,Central Park S & 6 Ave,40.765909,-73.976342,20831,Subscriber,1990,2
4,1312,2018-02-01 07:46:48.8750,2018-02-01 08:08:41.5430,72,W 52 St & 11 Ave,40.767272,-73.993929,435,W 21 St & 6 Ave,40.741740,-73.994156,15899,Subscriber,1957,1

In [8]:
apr_df = pd.read_csv(apr)
apr_df.head()

FileNotFoundError: [Errno 2] File b'Resources/Apr-NY.csv' does not exist: b'Resources/Apr-NY.csv'